hflan_player:
    path:     /list-players/
    defaults: { _controller: hflanPlayerBundle:Default:index }

hflan_player_list:
    path:     /list-players/{slug}
    defaults: { _controller: hflanPlayerBundle:Default:list }